plugins {
    id 'com.android.application'
}

def signingPropertiesFile = rootProject.file('signing.properties')
def signingProperties = new Properties()
if (signingPropertiesFile.exists()) {
    signingProperties.load(new FileInputStream(signingPropertiesFile))
}

android {
    namespace 'com.luanarabelo.treinodaluana.v12.wear'
    compileSdk 36

    signingConfigs {
        sharedTest {
            if (signingPropertiesFile.exists()) {
                storeFile rootProject.file(signingProperties['storeFile'])
                storePassword signingProperties['storePassword']
                keyAlias signingProperties['keyAlias']
                keyPassword signingProperties['keyPassword']
            }
        }
    }

    defaultConfig {
        applicationId 'com.luanarabelo.treinodaluana.v12'
        minSdk 30
        targetSdk 35
        versionCode 17
        versionName '16.0-watch8-test'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.xiaomitest'
            if (signingPropertiesFile.exists()) signingConfig signingConfigs.sharedTest
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-wearable:20.0.1'
}
